FROM python:3.10-slim
RUN mkdir workspace
WORKDIR /workspace
# Install git
RUN apt-get update && \
    apt-get install -y --no-install-recommends git && \
    rm -rf /var/lib/apt/lists/*
# Clean up
RUN apt-get clean
RUN pip install "poetry"
RUN poetry config virtualenvs.create false
COPY . .
ENV PYTHONPATH "${PYTHONPATH}:/workspace/src"
RUN poetry install
RUN rm -R *